#!/bin/bash

THIS="update-repo"

exiterr() {
	echo -e "$THIS: $@" 1>&2;
	exit 1 
}

if [ "$1" == "-h" ] || [ "$1" == "--h" ]
then
    exiterr "Updates all repositories below a base directory.\n\nUSAGE:  $THIS [base dir]\n"
fi

fpath="${1:-.}"

while IFS=$'\n' read -r rdir
do
	[[ "$rdir" =~ ^(.+/(.+)/)\.(git|hg|svn)$ ]]
	tool="${BASH_REMATCH[3]}"
	dir="${BASH_REMATCH[1]}"
	name="${BASH_REMATCH[2]}"

	printf "%s\t%s\t" "$name" "$tool"

	case "$tool" in
		git)
			cd "$dir"
			git fetch --all
			#git reset --hard HEAD
			git reset --hard origin/master
			#git rev-parse HEAD
			git log -n 1 --oneline --decorate origin/master
			cd ..
		;;
		hg)
			cd "$dir"
			hg update --clean
                        hg id -i | grep -Eo '[a-f0-9]+'
			cd ..
			
		;;
		svn)
			cd "$dir"
			svn revert -R .
			svn update
                        svn info --show-item revision
			cd ..
		;;
		*)
			echo "unknown"
		;;
	esac

done < <(find "$fpath" -mindepth 2 -maxdepth 2 -type d -name ".git" -o -name ".svn" -o -name ".hg")
